version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: antd
    versions:
    - 4.10.0
    - 4.12.2
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.15.0
    - 4.15.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.0
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - 6.0.5
    - 6.1.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
